version: "3.8"

services:
  # Serviço do PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: api-node-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: 5432
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - api-network

  # Serviço da API Node.js
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: api-node-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - api-network
    volumes:
      - ..:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  api-network:
    driver: bridge
